// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinellyApi.Data;

#nullable disable

namespace WinellyApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260120075841_ModifiedWineAndGrapeModel")]
    partial class ModifiedWineAndGrapeModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("WinellyApi.Models.Grape", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Grapes");
                });

            modelBuilder.Entity("WinellyApi.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WineryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WineId");

                    b.HasIndex("WineryId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("WinellyApi.Models.Wine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AlcoholContent")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Taste")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WineryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WineryId");

                    b.ToTable("Wines");
                });

            modelBuilder.Entity("WinellyApi.Models.Wine_GrapeConnection", b =>
                {
                    b.Property<int>("WineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GrapeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WineId", "GrapeId");

                    b.HasIndex("GrapeId");

                    b.ToTable("Wine_GrapeConnections");
                });

            modelBuilder.Entity("WinellyApi.Models.Winery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EstablishedYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Wineries");
                });

            modelBuilder.Entity("WinellyApi.Models.Rating", b =>
                {
                    b.HasOne("WinellyApi.Models.Wine", null)
                        .WithMany("Ratings")
                        .HasForeignKey("WineId");

                    b.HasOne("WinellyApi.Models.Winery", "Winery")
                        .WithMany()
                        .HasForeignKey("WineryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Winery");
                });

            modelBuilder.Entity("WinellyApi.Models.Wine", b =>
                {
                    b.HasOne("WinellyApi.Models.Winery", "Winery")
                        .WithMany("Wines")
                        .HasForeignKey("WineryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Winery");
                });

            modelBuilder.Entity("WinellyApi.Models.Wine_GrapeConnection", b =>
                {
                    b.HasOne("WinellyApi.Models.Grape", "Grape")
                        .WithMany("Wine_GrapeConnections")
                        .HasForeignKey("GrapeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WinellyApi.Models.Wine", "Wine")
                        .WithMany("Wine_GrapeConnections")
                        .HasForeignKey("WineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grape");

                    b.Navigation("Wine");
                });

            modelBuilder.Entity("WinellyApi.Models.Grape", b =>
                {
                    b.Navigation("Wine_GrapeConnections");
                });

            modelBuilder.Entity("WinellyApi.Models.Wine", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("Wine_GrapeConnections");
                });

            modelBuilder.Entity("WinellyApi.Models.Winery", b =>
                {
                    b.Navigation("Wines");
                });
#pragma warning restore 612, 618
        }
    }
}
